# Use container-based infrastructure
sudo: false

language: scala

#This forces the use of oraclejdk8, we don't support higher yet
#https://docs.travis-ci.com/user/reference/osx#jdk-and-os-x
os:
  - linux
  - osx

scala:
  - 2.11.12
  - 2.12.7

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

before_install:
  - wget https://bitcoincore.org/bin/bitcoin-core-0.16.3/bitcoin-0.16.3-x86_64-linux-gnu.tar.gz
  - tar -xzf bitcoin-0.16.3-x86_64-linux-gnu.tar.gz
  - cd bitcoin-0.16.3/bin
  - chmod +x bitcoin{d,-cli}
  - export PATH=$PATH:$(pwd)
  - cd ../..

install:
  - wget https://github.com/ACINQ/eclair/releases/download/v0.2-beta8/eclair-node-0.2-beta8-52821b8.jar 
  - export ECLAIR_PATH=$(pwd)

script:
  - sbt ++$TRAVIS_SCALA_VERSION coverage test &&
    sbt ++$TRAVIS_SCALA_VERSION core/coverageReport &&
    sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coveralls
